// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stop_sound.proto

package de.bwueller.environment.protocol;

public final class StopSound {
  private StopSound() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StopSoundRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StopSoundRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional string sound = 1;</code>
     */
    java.lang.String getSound();
    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional string sound = 1;</code>
     */
    com.google.protobuf.ByteString
        getSoundBytes();

    /**
     * <code>optional uint32 delay = 2;</code>
     */
    int getDelay();

    /**
     * <code>optional uint32 duration = 3;</code>
     */
    int getDuration();
  }
  /**
   * Protobuf type {@code StopSoundRequest}
   */
  public  static final class StopSoundRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StopSoundRequest)
      StopSoundRequestOrBuilder {
    // Use StopSoundRequest.newBuilder() to construct.
    private StopSoundRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StopSoundRequest() {
      sound_ = "";
      delay_ = 0;
      duration_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StopSoundRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sound_ = s;
              break;
            }
            case 16: {

              delay_ = input.readUInt32();
              break;
            }
            case 24: {

              duration_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.bwueller.environment.protocol.StopSound.internal_static_StopSoundRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.bwueller.environment.protocol.StopSound.internal_static_StopSoundRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.bwueller.environment.protocol.StopSound.StopSoundRequest.class, de.bwueller.environment.protocol.StopSound.StopSoundRequest.Builder.class);
    }

    public static final int SOUND_FIELD_NUMBER = 1;
    private volatile java.lang.Object sound_;
    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional string sound = 1;</code>
     */
    public java.lang.String getSound() {
      java.lang.Object ref = sound_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sound_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional string sound = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSoundBytes() {
      java.lang.Object ref = sound_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sound_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELAY_FIELD_NUMBER = 2;
    private int delay_;
    /**
     * <code>optional uint32 delay = 2;</code>
     */
    public int getDelay() {
      return delay_;
    }

    public static final int DURATION_FIELD_NUMBER = 3;
    private int duration_;
    /**
     * <code>optional uint32 duration = 3;</code>
     */
    public int getDuration() {
      return duration_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSoundBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sound_);
      }
      if (delay_ != 0) {
        output.writeUInt32(2, delay_);
      }
      if (duration_ != 0) {
        output.writeUInt32(3, duration_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSoundBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sound_);
      }
      if (delay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, delay_);
      }
      if (duration_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, duration_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.bwueller.environment.protocol.StopSound.StopSoundRequest)) {
        return super.equals(obj);
      }
      de.bwueller.environment.protocol.StopSound.StopSoundRequest other = (de.bwueller.environment.protocol.StopSound.StopSoundRequest) obj;

      boolean result = true;
      result = result && getSound()
          .equals(other.getSound());
      result = result && (getDelay()
          == other.getDelay());
      result = result && (getDuration()
          == other.getDuration());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SOUND_FIELD_NUMBER;
      hash = (53 * hash) + getSound().hashCode();
      hash = (37 * hash) + DELAY_FIELD_NUMBER;
      hash = (53 * hash) + getDelay();
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getDuration();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.bwueller.environment.protocol.StopSound.StopSoundRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.bwueller.environment.protocol.StopSound.StopSoundRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StopSoundRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StopSoundRequest)
        de.bwueller.environment.protocol.StopSound.StopSoundRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.bwueller.environment.protocol.StopSound.internal_static_StopSoundRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.bwueller.environment.protocol.StopSound.internal_static_StopSoundRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.bwueller.environment.protocol.StopSound.StopSoundRequest.class, de.bwueller.environment.protocol.StopSound.StopSoundRequest.Builder.class);
      }

      // Construct using de.bwueller.environment.protocol.StopSound.StopSoundRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sound_ = "";

        delay_ = 0;

        duration_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.bwueller.environment.protocol.StopSound.internal_static_StopSoundRequest_descriptor;
      }

      public de.bwueller.environment.protocol.StopSound.StopSoundRequest getDefaultInstanceForType() {
        return de.bwueller.environment.protocol.StopSound.StopSoundRequest.getDefaultInstance();
      }

      public de.bwueller.environment.protocol.StopSound.StopSoundRequest build() {
        de.bwueller.environment.protocol.StopSound.StopSoundRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.bwueller.environment.protocol.StopSound.StopSoundRequest buildPartial() {
        de.bwueller.environment.protocol.StopSound.StopSoundRequest result = new de.bwueller.environment.protocol.StopSound.StopSoundRequest(this);
        result.sound_ = sound_;
        result.delay_ = delay_;
        result.duration_ = duration_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.bwueller.environment.protocol.StopSound.StopSoundRequest) {
          return mergeFrom((de.bwueller.environment.protocol.StopSound.StopSoundRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.bwueller.environment.protocol.StopSound.StopSoundRequest other) {
        if (other == de.bwueller.environment.protocol.StopSound.StopSoundRequest.getDefaultInstance()) return this;
        if (!other.getSound().isEmpty()) {
          sound_ = other.sound_;
          onChanged();
        }
        if (other.getDelay() != 0) {
          setDelay(other.getDelay());
        }
        if (other.getDuration() != 0) {
          setDuration(other.getDuration());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.bwueller.environment.protocol.StopSound.StopSoundRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.bwueller.environment.protocol.StopSound.StopSoundRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sound_ = "";
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional string sound = 1;</code>
       */
      public java.lang.String getSound() {
        java.lang.Object ref = sound_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sound_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional string sound = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSoundBytes() {
        java.lang.Object ref = sound_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sound_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional string sound = 1;</code>
       */
      public Builder setSound(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sound_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional string sound = 1;</code>
       */
      public Builder clearSound() {
        
        sound_ = getDefaultInstance().getSound();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional string sound = 1;</code>
       */
      public Builder setSoundBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sound_ = value;
        onChanged();
        return this;
      }

      private int delay_ ;
      /**
       * <code>optional uint32 delay = 2;</code>
       */
      public int getDelay() {
        return delay_;
      }
      /**
       * <code>optional uint32 delay = 2;</code>
       */
      public Builder setDelay(int value) {
        
        delay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 delay = 2;</code>
       */
      public Builder clearDelay() {
        
        delay_ = 0;
        onChanged();
        return this;
      }

      private int duration_ ;
      /**
       * <code>optional uint32 duration = 3;</code>
       */
      public int getDuration() {
        return duration_;
      }
      /**
       * <code>optional uint32 duration = 3;</code>
       */
      public Builder setDuration(int value) {
        
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 duration = 3;</code>
       */
      public Builder clearDuration() {
        
        duration_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:StopSoundRequest)
    }

    // @@protoc_insertion_point(class_scope:StopSoundRequest)
    private static final de.bwueller.environment.protocol.StopSound.StopSoundRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.bwueller.environment.protocol.StopSound.StopSoundRequest();
    }

    public static de.bwueller.environment.protocol.StopSound.StopSoundRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StopSoundRequest>
        PARSER = new com.google.protobuf.AbstractParser<StopSoundRequest>() {
      public StopSoundRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StopSoundRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StopSoundRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StopSoundRequest> getParserForType() {
      return PARSER;
    }

    public de.bwueller.environment.protocol.StopSound.StopSoundRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StopSoundResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StopSoundResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string sound = 1;</code>
     */
    java.lang.String getSound();
    /**
     * <code>optional string sound = 1;</code>
     */
    com.google.protobuf.ByteString
        getSoundBytes();
  }
  /**
   * Protobuf type {@code StopSoundResponse}
   */
  public  static final class StopSoundResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StopSoundResponse)
      StopSoundResponseOrBuilder {
    // Use StopSoundResponse.newBuilder() to construct.
    private StopSoundResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StopSoundResponse() {
      sound_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StopSoundResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sound_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.bwueller.environment.protocol.StopSound.internal_static_StopSoundResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.bwueller.environment.protocol.StopSound.internal_static_StopSoundResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.bwueller.environment.protocol.StopSound.StopSoundResponse.class, de.bwueller.environment.protocol.StopSound.StopSoundResponse.Builder.class);
    }

    public static final int SOUND_FIELD_NUMBER = 1;
    private volatile java.lang.Object sound_;
    /**
     * <code>optional string sound = 1;</code>
     */
    public java.lang.String getSound() {
      java.lang.Object ref = sound_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sound_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sound = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSoundBytes() {
      java.lang.Object ref = sound_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sound_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSoundBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sound_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSoundBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sound_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.bwueller.environment.protocol.StopSound.StopSoundResponse)) {
        return super.equals(obj);
      }
      de.bwueller.environment.protocol.StopSound.StopSoundResponse other = (de.bwueller.environment.protocol.StopSound.StopSoundResponse) obj;

      boolean result = true;
      result = result && getSound()
          .equals(other.getSound());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SOUND_FIELD_NUMBER;
      hash = (53 * hash) + getSound().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.bwueller.environment.protocol.StopSound.StopSoundResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.StopSound.StopSoundResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.bwueller.environment.protocol.StopSound.StopSoundResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StopSoundResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StopSoundResponse)
        de.bwueller.environment.protocol.StopSound.StopSoundResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.bwueller.environment.protocol.StopSound.internal_static_StopSoundResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.bwueller.environment.protocol.StopSound.internal_static_StopSoundResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.bwueller.environment.protocol.StopSound.StopSoundResponse.class, de.bwueller.environment.protocol.StopSound.StopSoundResponse.Builder.class);
      }

      // Construct using de.bwueller.environment.protocol.StopSound.StopSoundResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sound_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.bwueller.environment.protocol.StopSound.internal_static_StopSoundResponse_descriptor;
      }

      public de.bwueller.environment.protocol.StopSound.StopSoundResponse getDefaultInstanceForType() {
        return de.bwueller.environment.protocol.StopSound.StopSoundResponse.getDefaultInstance();
      }

      public de.bwueller.environment.protocol.StopSound.StopSoundResponse build() {
        de.bwueller.environment.protocol.StopSound.StopSoundResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.bwueller.environment.protocol.StopSound.StopSoundResponse buildPartial() {
        de.bwueller.environment.protocol.StopSound.StopSoundResponse result = new de.bwueller.environment.protocol.StopSound.StopSoundResponse(this);
        result.sound_ = sound_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.bwueller.environment.protocol.StopSound.StopSoundResponse) {
          return mergeFrom((de.bwueller.environment.protocol.StopSound.StopSoundResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.bwueller.environment.protocol.StopSound.StopSoundResponse other) {
        if (other == de.bwueller.environment.protocol.StopSound.StopSoundResponse.getDefaultInstance()) return this;
        if (!other.getSound().isEmpty()) {
          sound_ = other.sound_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.bwueller.environment.protocol.StopSound.StopSoundResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.bwueller.environment.protocol.StopSound.StopSoundResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sound_ = "";
      /**
       * <code>optional string sound = 1;</code>
       */
      public java.lang.String getSound() {
        java.lang.Object ref = sound_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sound_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sound = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSoundBytes() {
        java.lang.Object ref = sound_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sound_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sound = 1;</code>
       */
      public Builder setSound(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sound = 1;</code>
       */
      public Builder clearSound() {
        
        sound_ = getDefaultInstance().getSound();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sound = 1;</code>
       */
      public Builder setSoundBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sound_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:StopSoundResponse)
    }

    // @@protoc_insertion_point(class_scope:StopSoundResponse)
    private static final de.bwueller.environment.protocol.StopSound.StopSoundResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.bwueller.environment.protocol.StopSound.StopSoundResponse();
    }

    public static de.bwueller.environment.protocol.StopSound.StopSoundResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StopSoundResponse>
        PARSER = new com.google.protobuf.AbstractParser<StopSoundResponse>() {
      public StopSoundResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StopSoundResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StopSoundResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StopSoundResponse> getParserForType() {
      return PARSER;
    }

    public de.bwueller.environment.protocol.StopSound.StopSoundResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StopSoundRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StopSoundRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StopSoundResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StopSoundResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020stop_sound.proto\032\rgeneral.proto\"B\n\020Sto" +
      "pSoundRequest\022\r\n\005sound\030\001 \001(\t\022\r\n\005delay\030\002 " +
      "\001(\r\022\020\n\010duration\030\003 \001(\r\"\"\n\021StopSoundRespon" +
      "se\022\r\n\005sound\030\001 \001(\tB\"\n de.bwueller.environ" +
      "ment.protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.bwueller.environment.protocol.General.getDescriptor(),
        }, assigner);
    internal_static_StopSoundRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StopSoundRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StopSoundRequest_descriptor,
        new java.lang.String[] { "Sound", "Delay", "Duration", });
    internal_static_StopSoundResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StopSoundResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StopSoundResponse_descriptor,
        new java.lang.String[] { "Sound", });
    de.bwueller.environment.protocol.General.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
