// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_sound_rate.proto

package de.bwueller.environment.protocol;

public final class UpdateSoundRate {
  private UpdateSoundRate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateSoundRateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UpdateSoundRateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional string sound = 2;</code>
     */
    java.lang.String getSound();
    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional string sound = 2;</code>
     */
    com.google.protobuf.ByteString
        getSoundBytes();

    /**
     * <code>optional double rate = 3;</code>
     */
    double getRate();
  }
  /**
   * Protobuf type {@code UpdateSoundRateRequest}
   */
  public  static final class UpdateSoundRateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UpdateSoundRateRequest)
      UpdateSoundRateRequestOrBuilder {
    // Use UpdateSoundRateRequest.newBuilder() to construct.
    private UpdateSoundRateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateSoundRateRequest() {
      sound_ = "";
      rate_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateSoundRateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sound_ = s;
              break;
            }
            case 25: {

              rate_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.bwueller.environment.protocol.UpdateSoundRate.internal_static_UpdateSoundRateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.bwueller.environment.protocol.UpdateSoundRate.internal_static_UpdateSoundRateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest.class, de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest.Builder.class);
    }

    public static final int SOUND_FIELD_NUMBER = 2;
    private volatile java.lang.Object sound_;
    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional string sound = 2;</code>
     */
    public java.lang.String getSound() {
      java.lang.Object ref = sound_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sound_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional string sound = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSoundBytes() {
      java.lang.Object ref = sound_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sound_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RATE_FIELD_NUMBER = 3;
    private double rate_;
    /**
     * <code>optional double rate = 3;</code>
     */
    public double getRate() {
      return rate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSoundBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sound_);
      }
      if (rate_ != 0D) {
        output.writeDouble(3, rate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSoundBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sound_);
      }
      if (rate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, rate_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest)) {
        return super.equals(obj);
      }
      de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest other = (de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest) obj;

      boolean result = true;
      result = result && getSound()
          .equals(other.getSound());
      result = result && (
          java.lang.Double.doubleToLongBits(getRate())
          == java.lang.Double.doubleToLongBits(
              other.getRate()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SOUND_FIELD_NUMBER;
      hash = (53 * hash) + getSound().hashCode();
      hash = (37 * hash) + RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRate()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UpdateSoundRateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UpdateSoundRateRequest)
        de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.bwueller.environment.protocol.UpdateSoundRate.internal_static_UpdateSoundRateRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.bwueller.environment.protocol.UpdateSoundRate.internal_static_UpdateSoundRateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest.class, de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest.Builder.class);
      }

      // Construct using de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sound_ = "";

        rate_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.bwueller.environment.protocol.UpdateSoundRate.internal_static_UpdateSoundRateRequest_descriptor;
      }

      public de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest getDefaultInstanceForType() {
        return de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest.getDefaultInstance();
      }

      public de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest build() {
        de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest buildPartial() {
        de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest result = new de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest(this);
        result.sound_ = sound_;
        result.rate_ = rate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest) {
          return mergeFrom((de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest other) {
        if (other == de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest.getDefaultInstance()) return this;
        if (!other.getSound().isEmpty()) {
          sound_ = other.sound_;
          onChanged();
        }
        if (other.getRate() != 0D) {
          setRate(other.getRate());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sound_ = "";
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional string sound = 2;</code>
       */
      public java.lang.String getSound() {
        java.lang.Object ref = sound_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sound_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional string sound = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSoundBytes() {
        java.lang.Object ref = sound_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sound_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional string sound = 2;</code>
       */
      public Builder setSound(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sound_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional string sound = 2;</code>
       */
      public Builder clearSound() {
        
        sound_ = getDefaultInstance().getSound();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional string sound = 2;</code>
       */
      public Builder setSoundBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sound_ = value;
        onChanged();
        return this;
      }

      private double rate_ ;
      /**
       * <code>optional double rate = 3;</code>
       */
      public double getRate() {
        return rate_;
      }
      /**
       * <code>optional double rate = 3;</code>
       */
      public Builder setRate(double value) {
        
        rate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double rate = 3;</code>
       */
      public Builder clearRate() {
        
        rate_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UpdateSoundRateRequest)
    }

    // @@protoc_insertion_point(class_scope:UpdateSoundRateRequest)
    private static final de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest();
    }

    public static de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateSoundRateRequest>
        PARSER = new com.google.protobuf.AbstractParser<UpdateSoundRateRequest>() {
      public UpdateSoundRateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdateSoundRateRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateSoundRateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateSoundRateRequest> getParserForType() {
      return PARSER;
    }

    public de.bwueller.environment.protocol.UpdateSoundRate.UpdateSoundRateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateSoundRateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateSoundRateRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027update_sound_rate.proto\032\rgeneral.proto" +
      "\"5\n\026UpdateSoundRateRequest\022\r\n\005sound\030\002 \001(" +
      "\t\022\014\n\004rate\030\003 \001(\001B\"\n de.bwueller.environme" +
      "nt.protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.bwueller.environment.protocol.General.getDescriptor(),
        }, assigner);
    internal_static_UpdateSoundRateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UpdateSoundRateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateSoundRateRequest_descriptor,
        new java.lang.String[] { "Sound", "Rate", });
    de.bwueller.environment.protocol.General.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
