// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_actor_user_meta.proto

package de.bwueller.environment.protocol;

public final class UpdateActorUserMeta {
  private UpdateActorUserMeta() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateActorUserMetaRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UpdateActorUserMetaRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string identifier = 1;</code>
     */
    java.lang.String getIdentifier();
    /**
     * <code>optional string identifier = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdentifierBytes();

    /**
     * <code>repeated .Meta meta = 2;</code>
     */
    java.util.List<de.bwueller.environment.protocol.General.Meta> 
        getMetaList();
    /**
     * <code>repeated .Meta meta = 2;</code>
     */
    de.bwueller.environment.protocol.General.Meta getMeta(int index);
    /**
     * <code>repeated .Meta meta = 2;</code>
     */
    int getMetaCount();
    /**
     * <code>repeated .Meta meta = 2;</code>
     */
    java.util.List<? extends de.bwueller.environment.protocol.General.MetaOrBuilder> 
        getMetaOrBuilderList();
    /**
     * <code>repeated .Meta meta = 2;</code>
     */
    de.bwueller.environment.protocol.General.MetaOrBuilder getMetaOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code UpdateActorUserMetaRequest}
   */
  public  static final class UpdateActorUserMetaRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UpdateActorUserMetaRequest)
      UpdateActorUserMetaRequestOrBuilder {
    // Use UpdateActorUserMetaRequest.newBuilder() to construct.
    private UpdateActorUserMetaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateActorUserMetaRequest() {
      identifier_ = "";
      meta_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateActorUserMetaRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              identifier_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                meta_ = new java.util.ArrayList<de.bwueller.environment.protocol.General.Meta>();
                mutable_bitField0_ |= 0x00000002;
              }
              meta_.add(
                  input.readMessage(de.bwueller.environment.protocol.General.Meta.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          meta_ = java.util.Collections.unmodifiableList(meta_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.bwueller.environment.protocol.UpdateActorUserMeta.internal_static_UpdateActorUserMetaRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.bwueller.environment.protocol.UpdateActorUserMeta.internal_static_UpdateActorUserMetaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest.class, de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest.Builder.class);
    }

    private int bitField0_;
    public static final int IDENTIFIER_FIELD_NUMBER = 1;
    private volatile java.lang.Object identifier_;
    /**
     * <code>optional string identifier = 1;</code>
     */
    public java.lang.String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        identifier_ = s;
        return s;
      }
    }
    /**
     * <code>optional string identifier = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int META_FIELD_NUMBER = 2;
    private java.util.List<de.bwueller.environment.protocol.General.Meta> meta_;
    /**
     * <code>repeated .Meta meta = 2;</code>
     */
    public java.util.List<de.bwueller.environment.protocol.General.Meta> getMetaList() {
      return meta_;
    }
    /**
     * <code>repeated .Meta meta = 2;</code>
     */
    public java.util.List<? extends de.bwueller.environment.protocol.General.MetaOrBuilder> 
        getMetaOrBuilderList() {
      return meta_;
    }
    /**
     * <code>repeated .Meta meta = 2;</code>
     */
    public int getMetaCount() {
      return meta_.size();
    }
    /**
     * <code>repeated .Meta meta = 2;</code>
     */
    public de.bwueller.environment.protocol.General.Meta getMeta(int index) {
      return meta_.get(index);
    }
    /**
     * <code>repeated .Meta meta = 2;</code>
     */
    public de.bwueller.environment.protocol.General.MetaOrBuilder getMetaOrBuilder(
        int index) {
      return meta_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdentifierBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, identifier_);
      }
      for (int i = 0; i < meta_.size(); i++) {
        output.writeMessage(2, meta_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdentifierBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, identifier_);
      }
      for (int i = 0; i < meta_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, meta_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest)) {
        return super.equals(obj);
      }
      de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest other = (de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest) obj;

      boolean result = true;
      result = result && getIdentifier()
          .equals(other.getIdentifier());
      result = result && getMetaList()
          .equals(other.getMetaList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifier().hashCode();
      if (getMetaCount() > 0) {
        hash = (37 * hash) + META_FIELD_NUMBER;
        hash = (53 * hash) + getMetaList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UpdateActorUserMetaRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UpdateActorUserMetaRequest)
        de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.bwueller.environment.protocol.UpdateActorUserMeta.internal_static_UpdateActorUserMetaRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.bwueller.environment.protocol.UpdateActorUserMeta.internal_static_UpdateActorUserMetaRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest.class, de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest.Builder.class);
      }

      // Construct using de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMetaFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        identifier_ = "";

        if (metaBuilder_ == null) {
          meta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          metaBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.bwueller.environment.protocol.UpdateActorUserMeta.internal_static_UpdateActorUserMetaRequest_descriptor;
      }

      public de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest getDefaultInstanceForType() {
        return de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest.getDefaultInstance();
      }

      public de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest build() {
        de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest buildPartial() {
        de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest result = new de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.identifier_ = identifier_;
        if (metaBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            meta_ = java.util.Collections.unmodifiableList(meta_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.meta_ = meta_;
        } else {
          result.meta_ = metaBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest) {
          return mergeFrom((de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest other) {
        if (other == de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest.getDefaultInstance()) return this;
        if (!other.getIdentifier().isEmpty()) {
          identifier_ = other.identifier_;
          onChanged();
        }
        if (metaBuilder_ == null) {
          if (!other.meta_.isEmpty()) {
            if (meta_.isEmpty()) {
              meta_ = other.meta_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMetaIsMutable();
              meta_.addAll(other.meta_);
            }
            onChanged();
          }
        } else {
          if (!other.meta_.isEmpty()) {
            if (metaBuilder_.isEmpty()) {
              metaBuilder_.dispose();
              metaBuilder_ = null;
              meta_ = other.meta_;
              bitField0_ = (bitField0_ & ~0x00000002);
              metaBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMetaFieldBuilder() : null;
            } else {
              metaBuilder_.addAllMessages(other.meta_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object identifier_ = "";
      /**
       * <code>optional string identifier = 1;</code>
       */
      public java.lang.String getIdentifier() {
        java.lang.Object ref = identifier_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          identifier_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string identifier = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdentifierBytes() {
        java.lang.Object ref = identifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string identifier = 1;</code>
       */
      public Builder setIdentifier(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string identifier = 1;</code>
       */
      public Builder clearIdentifier() {
        
        identifier_ = getDefaultInstance().getIdentifier();
        onChanged();
        return this;
      }
      /**
       * <code>optional string identifier = 1;</code>
       */
      public Builder setIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        identifier_ = value;
        onChanged();
        return this;
      }

      private java.util.List<de.bwueller.environment.protocol.General.Meta> meta_ =
        java.util.Collections.emptyList();
      private void ensureMetaIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          meta_ = new java.util.ArrayList<de.bwueller.environment.protocol.General.Meta>(meta_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          de.bwueller.environment.protocol.General.Meta, de.bwueller.environment.protocol.General.Meta.Builder, de.bwueller.environment.protocol.General.MetaOrBuilder> metaBuilder_;

      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public java.util.List<de.bwueller.environment.protocol.General.Meta> getMetaList() {
        if (metaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(meta_);
        } else {
          return metaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public int getMetaCount() {
        if (metaBuilder_ == null) {
          return meta_.size();
        } else {
          return metaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public de.bwueller.environment.protocol.General.Meta getMeta(int index) {
        if (metaBuilder_ == null) {
          return meta_.get(index);
        } else {
          return metaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public Builder setMeta(
          int index, de.bwueller.environment.protocol.General.Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaIsMutable();
          meta_.set(index, value);
          onChanged();
        } else {
          metaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public Builder setMeta(
          int index, de.bwueller.environment.protocol.General.Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.set(index, builderForValue.build());
          onChanged();
        } else {
          metaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public Builder addMeta(de.bwueller.environment.protocol.General.Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaIsMutable();
          meta_.add(value);
          onChanged();
        } else {
          metaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public Builder addMeta(
          int index, de.bwueller.environment.protocol.General.Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaIsMutable();
          meta_.add(index, value);
          onChanged();
        } else {
          metaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public Builder addMeta(
          de.bwueller.environment.protocol.General.Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.add(builderForValue.build());
          onChanged();
        } else {
          metaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public Builder addMeta(
          int index, de.bwueller.environment.protocol.General.Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.add(index, builderForValue.build());
          onChanged();
        } else {
          metaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public Builder addAllMeta(
          java.lang.Iterable<? extends de.bwueller.environment.protocol.General.Meta> values) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, meta_);
          onChanged();
        } else {
          metaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public Builder clearMeta() {
        if (metaBuilder_ == null) {
          meta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          metaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public Builder removeMeta(int index) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.remove(index);
          onChanged();
        } else {
          metaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public de.bwueller.environment.protocol.General.Meta.Builder getMetaBuilder(
          int index) {
        return getMetaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public de.bwueller.environment.protocol.General.MetaOrBuilder getMetaOrBuilder(
          int index) {
        if (metaBuilder_ == null) {
          return meta_.get(index);  } else {
          return metaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public java.util.List<? extends de.bwueller.environment.protocol.General.MetaOrBuilder> 
           getMetaOrBuilderList() {
        if (metaBuilder_ != null) {
          return metaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(meta_);
        }
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public de.bwueller.environment.protocol.General.Meta.Builder addMetaBuilder() {
        return getMetaFieldBuilder().addBuilder(
            de.bwueller.environment.protocol.General.Meta.getDefaultInstance());
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public de.bwueller.environment.protocol.General.Meta.Builder addMetaBuilder(
          int index) {
        return getMetaFieldBuilder().addBuilder(
            index, de.bwueller.environment.protocol.General.Meta.getDefaultInstance());
      }
      /**
       * <code>repeated .Meta meta = 2;</code>
       */
      public java.util.List<de.bwueller.environment.protocol.General.Meta.Builder> 
           getMetaBuilderList() {
        return getMetaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          de.bwueller.environment.protocol.General.Meta, de.bwueller.environment.protocol.General.Meta.Builder, de.bwueller.environment.protocol.General.MetaOrBuilder> 
          getMetaFieldBuilder() {
        if (metaBuilder_ == null) {
          metaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              de.bwueller.environment.protocol.General.Meta, de.bwueller.environment.protocol.General.Meta.Builder, de.bwueller.environment.protocol.General.MetaOrBuilder>(
                  meta_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          meta_ = null;
        }
        return metaBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UpdateActorUserMetaRequest)
    }

    // @@protoc_insertion_point(class_scope:UpdateActorUserMetaRequest)
    private static final de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest();
    }

    public static de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateActorUserMetaRequest>
        PARSER = new com.google.protobuf.AbstractParser<UpdateActorUserMetaRequest>() {
      public UpdateActorUserMetaRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdateActorUserMetaRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateActorUserMetaRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateActorUserMetaRequest> getParserForType() {
      return PARSER;
    }

    public de.bwueller.environment.protocol.UpdateActorUserMeta.UpdateActorUserMetaRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateActorUserMetaRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateActorUserMetaRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034update_actor_user_meta.proto\032\rgeneral." +
      "proto\"E\n\032UpdateActorUserMetaRequest\022\022\n\ni" +
      "dentifier\030\001 \001(\t\022\023\n\004meta\030\002 \003(\0132\005.MetaB\"\n " +
      "de.bwueller.environment.protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.bwueller.environment.protocol.General.getDescriptor(),
        }, assigner);
    internal_static_UpdateActorUserMetaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UpdateActorUserMetaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateActorUserMetaRequest_descriptor,
        new java.lang.String[] { "Identifier", "Meta", });
    de.bwueller.environment.protocol.General.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
