// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: play_sound.proto

package de.bwueller.environment.protocol;

public final class PlaySound {
  private PlaySound() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlaySoundRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlaySoundRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * User identifier.
     * </pre>
     *
     * <code>optional .UUID user = 1;</code>
     */
    boolean hasUser();
    /**
     * <pre>
     * User identifier.
     * </pre>
     *
     * <code>optional .UUID user = 1;</code>
     */
    de.bwueller.environment.protocol.General.UUID getUser();
    /**
     * <pre>
     * User identifier.
     * </pre>
     *
     * <code>optional .UUID user = 1;</code>
     */
    de.bwueller.environment.protocol.General.UUIDOrBuilder getUserOrBuilder();

    /**
     * <pre>
     * Sound identifier generated by the actor.
     * </pre>
     *
     * <code>optional .UUID identifier = 2;</code>
     */
    boolean hasIdentifier();
    /**
     * <pre>
     * Sound identifier generated by the actor.
     * </pre>
     *
     * <code>optional .UUID identifier = 2;</code>
     */
    de.bwueller.environment.protocol.General.UUID getIdentifier();
    /**
     * <pre>
     * Sound identifier generated by the actor.
     * </pre>
     *
     * <code>optional .UUID identifier = 2;</code>
     */
    de.bwueller.environment.protocol.General.UUIDOrBuilder getIdentifierOrBuilder();

    /**
     * <code>optional .Sound intro = 3;</code>
     */
    boolean hasIntro();
    /**
     * <code>optional .Sound intro = 3;</code>
     */
    de.bwueller.environment.protocol.PlaySound.Sound getIntro();
    /**
     * <code>optional .Sound intro = 3;</code>
     */
    de.bwueller.environment.protocol.PlaySound.SoundOrBuilder getIntroOrBuilder();

    /**
     * <code>optional .Sound sound = 4;</code>
     */
    boolean hasSound();
    /**
     * <code>optional .Sound sound = 4;</code>
     */
    de.bwueller.environment.protocol.PlaySound.Sound getSound();
    /**
     * <code>optional .Sound sound = 4;</code>
     */
    de.bwueller.environment.protocol.PlaySound.SoundOrBuilder getSoundOrBuilder();

    /**
     * <code>optional double volume = 5;</code>
     */
    double getVolume();

    /**
     * <code>optional double rate = 6;</code>
     */
    double getRate();

    /**
     * <code>optional bool loop = 7;</code>
     */
    boolean getLoop();
  }
  /**
   * Protobuf type {@code PlaySoundRequest}
   */
  public  static final class PlaySoundRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlaySoundRequest)
      PlaySoundRequestOrBuilder {
    // Use PlaySoundRequest.newBuilder() to construct.
    private PlaySoundRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlaySoundRequest() {
      volume_ = 0D;
      rate_ = 0D;
      loop_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PlaySoundRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              de.bwueller.environment.protocol.General.UUID.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(de.bwueller.environment.protocol.General.UUID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              de.bwueller.environment.protocol.General.UUID.Builder subBuilder = null;
              if (identifier_ != null) {
                subBuilder = identifier_.toBuilder();
              }
              identifier_ = input.readMessage(de.bwueller.environment.protocol.General.UUID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(identifier_);
                identifier_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              de.bwueller.environment.protocol.PlaySound.Sound.Builder subBuilder = null;
              if (intro_ != null) {
                subBuilder = intro_.toBuilder();
              }
              intro_ = input.readMessage(de.bwueller.environment.protocol.PlaySound.Sound.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(intro_);
                intro_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              de.bwueller.environment.protocol.PlaySound.Sound.Builder subBuilder = null;
              if (sound_ != null) {
                subBuilder = sound_.toBuilder();
              }
              sound_ = input.readMessage(de.bwueller.environment.protocol.PlaySound.Sound.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sound_);
                sound_ = subBuilder.buildPartial();
              }

              break;
            }
            case 41: {

              volume_ = input.readDouble();
              break;
            }
            case 49: {

              rate_ = input.readDouble();
              break;
            }
            case 56: {

              loop_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.bwueller.environment.protocol.PlaySound.internal_static_PlaySoundRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.bwueller.environment.protocol.PlaySound.internal_static_PlaySoundRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.bwueller.environment.protocol.PlaySound.PlaySoundRequest.class, de.bwueller.environment.protocol.PlaySound.PlaySoundRequest.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private de.bwueller.environment.protocol.General.UUID user_;
    /**
     * <pre>
     * User identifier.
     * </pre>
     *
     * <code>optional .UUID user = 1;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <pre>
     * User identifier.
     * </pre>
     *
     * <code>optional .UUID user = 1;</code>
     */
    public de.bwueller.environment.protocol.General.UUID getUser() {
      return user_ == null ? de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : user_;
    }
    /**
     * <pre>
     * User identifier.
     * </pre>
     *
     * <code>optional .UUID user = 1;</code>
     */
    public de.bwueller.environment.protocol.General.UUIDOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 2;
    private de.bwueller.environment.protocol.General.UUID identifier_;
    /**
     * <pre>
     * Sound identifier generated by the actor.
     * </pre>
     *
     * <code>optional .UUID identifier = 2;</code>
     */
    public boolean hasIdentifier() {
      return identifier_ != null;
    }
    /**
     * <pre>
     * Sound identifier generated by the actor.
     * </pre>
     *
     * <code>optional .UUID identifier = 2;</code>
     */
    public de.bwueller.environment.protocol.General.UUID getIdentifier() {
      return identifier_ == null ? de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : identifier_;
    }
    /**
     * <pre>
     * Sound identifier generated by the actor.
     * </pre>
     *
     * <code>optional .UUID identifier = 2;</code>
     */
    public de.bwueller.environment.protocol.General.UUIDOrBuilder getIdentifierOrBuilder() {
      return getIdentifier();
    }

    public static final int INTRO_FIELD_NUMBER = 3;
    private de.bwueller.environment.protocol.PlaySound.Sound intro_;
    /**
     * <code>optional .Sound intro = 3;</code>
     */
    public boolean hasIntro() {
      return intro_ != null;
    }
    /**
     * <code>optional .Sound intro = 3;</code>
     */
    public de.bwueller.environment.protocol.PlaySound.Sound getIntro() {
      return intro_ == null ? de.bwueller.environment.protocol.PlaySound.Sound.getDefaultInstance() : intro_;
    }
    /**
     * <code>optional .Sound intro = 3;</code>
     */
    public de.bwueller.environment.protocol.PlaySound.SoundOrBuilder getIntroOrBuilder() {
      return getIntro();
    }

    public static final int SOUND_FIELD_NUMBER = 4;
    private de.bwueller.environment.protocol.PlaySound.Sound sound_;
    /**
     * <code>optional .Sound sound = 4;</code>
     */
    public boolean hasSound() {
      return sound_ != null;
    }
    /**
     * <code>optional .Sound sound = 4;</code>
     */
    public de.bwueller.environment.protocol.PlaySound.Sound getSound() {
      return sound_ == null ? de.bwueller.environment.protocol.PlaySound.Sound.getDefaultInstance() : sound_;
    }
    /**
     * <code>optional .Sound sound = 4;</code>
     */
    public de.bwueller.environment.protocol.PlaySound.SoundOrBuilder getSoundOrBuilder() {
      return getSound();
    }

    public static final int VOLUME_FIELD_NUMBER = 5;
    private double volume_;
    /**
     * <code>optional double volume = 5;</code>
     */
    public double getVolume() {
      return volume_;
    }

    public static final int RATE_FIELD_NUMBER = 6;
    private double rate_;
    /**
     * <code>optional double rate = 6;</code>
     */
    public double getRate() {
      return rate_;
    }

    public static final int LOOP_FIELD_NUMBER = 7;
    private boolean loop_;
    /**
     * <code>optional bool loop = 7;</code>
     */
    public boolean getLoop() {
      return loop_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (user_ != null) {
        output.writeMessage(1, getUser());
      }
      if (identifier_ != null) {
        output.writeMessage(2, getIdentifier());
      }
      if (intro_ != null) {
        output.writeMessage(3, getIntro());
      }
      if (sound_ != null) {
        output.writeMessage(4, getSound());
      }
      if (volume_ != 0D) {
        output.writeDouble(5, volume_);
      }
      if (rate_ != 0D) {
        output.writeDouble(6, rate_);
      }
      if (loop_ != false) {
        output.writeBool(7, loop_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUser());
      }
      if (identifier_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getIdentifier());
      }
      if (intro_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getIntro());
      }
      if (sound_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSound());
      }
      if (volume_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, volume_);
      }
      if (rate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, rate_);
      }
      if (loop_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, loop_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.bwueller.environment.protocol.PlaySound.PlaySoundRequest)) {
        return super.equals(obj);
      }
      de.bwueller.environment.protocol.PlaySound.PlaySoundRequest other = (de.bwueller.environment.protocol.PlaySound.PlaySoundRequest) obj;

      boolean result = true;
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && (hasIdentifier() == other.hasIdentifier());
      if (hasIdentifier()) {
        result = result && getIdentifier()
            .equals(other.getIdentifier());
      }
      result = result && (hasIntro() == other.hasIntro());
      if (hasIntro()) {
        result = result && getIntro()
            .equals(other.getIntro());
      }
      result = result && (hasSound() == other.hasSound());
      if (hasSound()) {
        result = result && getSound()
            .equals(other.getSound());
      }
      result = result && (
          java.lang.Double.doubleToLongBits(getVolume())
          == java.lang.Double.doubleToLongBits(
              other.getVolume()));
      result = result && (
          java.lang.Double.doubleToLongBits(getRate())
          == java.lang.Double.doubleToLongBits(
              other.getRate()));
      result = result && (getLoop()
          == other.getLoop());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (hasIdentifier()) {
        hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getIdentifier().hashCode();
      }
      if (hasIntro()) {
        hash = (37 * hash) + INTRO_FIELD_NUMBER;
        hash = (53 * hash) + getIntro().hashCode();
      }
      if (hasSound()) {
        hash = (37 * hash) + SOUND_FIELD_NUMBER;
        hash = (53 * hash) + getSound().hashCode();
      }
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVolume()));
      hash = (37 * hash) + RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRate()));
      hash = (37 * hash) + LOOP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLoop());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.bwueller.environment.protocol.PlaySound.PlaySoundRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.bwueller.environment.protocol.PlaySound.PlaySoundRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlaySoundRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlaySoundRequest)
        de.bwueller.environment.protocol.PlaySound.PlaySoundRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.bwueller.environment.protocol.PlaySound.internal_static_PlaySoundRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.bwueller.environment.protocol.PlaySound.internal_static_PlaySoundRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.bwueller.environment.protocol.PlaySound.PlaySoundRequest.class, de.bwueller.environment.protocol.PlaySound.PlaySoundRequest.Builder.class);
      }

      // Construct using de.bwueller.environment.protocol.PlaySound.PlaySoundRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        if (identifierBuilder_ == null) {
          identifier_ = null;
        } else {
          identifier_ = null;
          identifierBuilder_ = null;
        }
        if (introBuilder_ == null) {
          intro_ = null;
        } else {
          intro_ = null;
          introBuilder_ = null;
        }
        if (soundBuilder_ == null) {
          sound_ = null;
        } else {
          sound_ = null;
          soundBuilder_ = null;
        }
        volume_ = 0D;

        rate_ = 0D;

        loop_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.bwueller.environment.protocol.PlaySound.internal_static_PlaySoundRequest_descriptor;
      }

      public de.bwueller.environment.protocol.PlaySound.PlaySoundRequest getDefaultInstanceForType() {
        return de.bwueller.environment.protocol.PlaySound.PlaySoundRequest.getDefaultInstance();
      }

      public de.bwueller.environment.protocol.PlaySound.PlaySoundRequest build() {
        de.bwueller.environment.protocol.PlaySound.PlaySoundRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.bwueller.environment.protocol.PlaySound.PlaySoundRequest buildPartial() {
        de.bwueller.environment.protocol.PlaySound.PlaySoundRequest result = new de.bwueller.environment.protocol.PlaySound.PlaySoundRequest(this);
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (identifierBuilder_ == null) {
          result.identifier_ = identifier_;
        } else {
          result.identifier_ = identifierBuilder_.build();
        }
        if (introBuilder_ == null) {
          result.intro_ = intro_;
        } else {
          result.intro_ = introBuilder_.build();
        }
        if (soundBuilder_ == null) {
          result.sound_ = sound_;
        } else {
          result.sound_ = soundBuilder_.build();
        }
        result.volume_ = volume_;
        result.rate_ = rate_;
        result.loop_ = loop_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.bwueller.environment.protocol.PlaySound.PlaySoundRequest) {
          return mergeFrom((de.bwueller.environment.protocol.PlaySound.PlaySoundRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.bwueller.environment.protocol.PlaySound.PlaySoundRequest other) {
        if (other == de.bwueller.environment.protocol.PlaySound.PlaySoundRequest.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasIdentifier()) {
          mergeIdentifier(other.getIdentifier());
        }
        if (other.hasIntro()) {
          mergeIntro(other.getIntro());
        }
        if (other.hasSound()) {
          mergeSound(other.getSound());
        }
        if (other.getVolume() != 0D) {
          setVolume(other.getVolume());
        }
        if (other.getRate() != 0D) {
          setRate(other.getRate());
        }
        if (other.getLoop() != false) {
          setLoop(other.getLoop());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.bwueller.environment.protocol.PlaySound.PlaySoundRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.bwueller.environment.protocol.PlaySound.PlaySoundRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private de.bwueller.environment.protocol.General.UUID user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder> userBuilder_;
      /**
       * <pre>
       * User identifier.
       * </pre>
       *
       * <code>optional .UUID user = 1;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <pre>
       * User identifier.
       * </pre>
       *
       * <code>optional .UUID user = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUID getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * User identifier.
       * </pre>
       *
       * <code>optional .UUID user = 1;</code>
       */
      public Builder setUser(de.bwueller.environment.protocol.General.UUID value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * User identifier.
       * </pre>
       *
       * <code>optional .UUID user = 1;</code>
       */
      public Builder setUser(
          de.bwueller.environment.protocol.General.UUID.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * User identifier.
       * </pre>
       *
       * <code>optional .UUID user = 1;</code>
       */
      public Builder mergeUser(de.bwueller.environment.protocol.General.UUID value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              de.bwueller.environment.protocol.General.UUID.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * User identifier.
       * </pre>
       *
       * <code>optional .UUID user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * User identifier.
       * </pre>
       *
       * <code>optional .UUID user = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUID.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * User identifier.
       * </pre>
       *
       * <code>optional .UUID user = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUIDOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : user_;
        }
      }
      /**
       * <pre>
       * User identifier.
       * </pre>
       *
       * <code>optional .UUID user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private de.bwueller.environment.protocol.General.UUID identifier_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder> identifierBuilder_;
      /**
       * <pre>
       * Sound identifier generated by the actor.
       * </pre>
       *
       * <code>optional .UUID identifier = 2;</code>
       */
      public boolean hasIdentifier() {
        return identifierBuilder_ != null || identifier_ != null;
      }
      /**
       * <pre>
       * Sound identifier generated by the actor.
       * </pre>
       *
       * <code>optional .UUID identifier = 2;</code>
       */
      public de.bwueller.environment.protocol.General.UUID getIdentifier() {
        if (identifierBuilder_ == null) {
          return identifier_ == null ? de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : identifier_;
        } else {
          return identifierBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Sound identifier generated by the actor.
       * </pre>
       *
       * <code>optional .UUID identifier = 2;</code>
       */
      public Builder setIdentifier(de.bwueller.environment.protocol.General.UUID value) {
        if (identifierBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          identifier_ = value;
          onChanged();
        } else {
          identifierBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Sound identifier generated by the actor.
       * </pre>
       *
       * <code>optional .UUID identifier = 2;</code>
       */
      public Builder setIdentifier(
          de.bwueller.environment.protocol.General.UUID.Builder builderForValue) {
        if (identifierBuilder_ == null) {
          identifier_ = builderForValue.build();
          onChanged();
        } else {
          identifierBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Sound identifier generated by the actor.
       * </pre>
       *
       * <code>optional .UUID identifier = 2;</code>
       */
      public Builder mergeIdentifier(de.bwueller.environment.protocol.General.UUID value) {
        if (identifierBuilder_ == null) {
          if (identifier_ != null) {
            identifier_ =
              de.bwueller.environment.protocol.General.UUID.newBuilder(identifier_).mergeFrom(value).buildPartial();
          } else {
            identifier_ = value;
          }
          onChanged();
        } else {
          identifierBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Sound identifier generated by the actor.
       * </pre>
       *
       * <code>optional .UUID identifier = 2;</code>
       */
      public Builder clearIdentifier() {
        if (identifierBuilder_ == null) {
          identifier_ = null;
          onChanged();
        } else {
          identifier_ = null;
          identifierBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Sound identifier generated by the actor.
       * </pre>
       *
       * <code>optional .UUID identifier = 2;</code>
       */
      public de.bwueller.environment.protocol.General.UUID.Builder getIdentifierBuilder() {
        
        onChanged();
        return getIdentifierFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Sound identifier generated by the actor.
       * </pre>
       *
       * <code>optional .UUID identifier = 2;</code>
       */
      public de.bwueller.environment.protocol.General.UUIDOrBuilder getIdentifierOrBuilder() {
        if (identifierBuilder_ != null) {
          return identifierBuilder_.getMessageOrBuilder();
        } else {
          return identifier_ == null ?
              de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : identifier_;
        }
      }
      /**
       * <pre>
       * Sound identifier generated by the actor.
       * </pre>
       *
       * <code>optional .UUID identifier = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder> 
          getIdentifierFieldBuilder() {
        if (identifierBuilder_ == null) {
          identifierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder>(
                  getIdentifier(),
                  getParentForChildren(),
                  isClean());
          identifier_ = null;
        }
        return identifierBuilder_;
      }

      private de.bwueller.environment.protocol.PlaySound.Sound intro_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.PlaySound.Sound, de.bwueller.environment.protocol.PlaySound.Sound.Builder, de.bwueller.environment.protocol.PlaySound.SoundOrBuilder> introBuilder_;
      /**
       * <code>optional .Sound intro = 3;</code>
       */
      public boolean hasIntro() {
        return introBuilder_ != null || intro_ != null;
      }
      /**
       * <code>optional .Sound intro = 3;</code>
       */
      public de.bwueller.environment.protocol.PlaySound.Sound getIntro() {
        if (introBuilder_ == null) {
          return intro_ == null ? de.bwueller.environment.protocol.PlaySound.Sound.getDefaultInstance() : intro_;
        } else {
          return introBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Sound intro = 3;</code>
       */
      public Builder setIntro(de.bwueller.environment.protocol.PlaySound.Sound value) {
        if (introBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          intro_ = value;
          onChanged();
        } else {
          introBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Sound intro = 3;</code>
       */
      public Builder setIntro(
          de.bwueller.environment.protocol.PlaySound.Sound.Builder builderForValue) {
        if (introBuilder_ == null) {
          intro_ = builderForValue.build();
          onChanged();
        } else {
          introBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Sound intro = 3;</code>
       */
      public Builder mergeIntro(de.bwueller.environment.protocol.PlaySound.Sound value) {
        if (introBuilder_ == null) {
          if (intro_ != null) {
            intro_ =
              de.bwueller.environment.protocol.PlaySound.Sound.newBuilder(intro_).mergeFrom(value).buildPartial();
          } else {
            intro_ = value;
          }
          onChanged();
        } else {
          introBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Sound intro = 3;</code>
       */
      public Builder clearIntro() {
        if (introBuilder_ == null) {
          intro_ = null;
          onChanged();
        } else {
          intro_ = null;
          introBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Sound intro = 3;</code>
       */
      public de.bwueller.environment.protocol.PlaySound.Sound.Builder getIntroBuilder() {
        
        onChanged();
        return getIntroFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Sound intro = 3;</code>
       */
      public de.bwueller.environment.protocol.PlaySound.SoundOrBuilder getIntroOrBuilder() {
        if (introBuilder_ != null) {
          return introBuilder_.getMessageOrBuilder();
        } else {
          return intro_ == null ?
              de.bwueller.environment.protocol.PlaySound.Sound.getDefaultInstance() : intro_;
        }
      }
      /**
       * <code>optional .Sound intro = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.PlaySound.Sound, de.bwueller.environment.protocol.PlaySound.Sound.Builder, de.bwueller.environment.protocol.PlaySound.SoundOrBuilder> 
          getIntroFieldBuilder() {
        if (introBuilder_ == null) {
          introBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              de.bwueller.environment.protocol.PlaySound.Sound, de.bwueller.environment.protocol.PlaySound.Sound.Builder, de.bwueller.environment.protocol.PlaySound.SoundOrBuilder>(
                  getIntro(),
                  getParentForChildren(),
                  isClean());
          intro_ = null;
        }
        return introBuilder_;
      }

      private de.bwueller.environment.protocol.PlaySound.Sound sound_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.PlaySound.Sound, de.bwueller.environment.protocol.PlaySound.Sound.Builder, de.bwueller.environment.protocol.PlaySound.SoundOrBuilder> soundBuilder_;
      /**
       * <code>optional .Sound sound = 4;</code>
       */
      public boolean hasSound() {
        return soundBuilder_ != null || sound_ != null;
      }
      /**
       * <code>optional .Sound sound = 4;</code>
       */
      public de.bwueller.environment.protocol.PlaySound.Sound getSound() {
        if (soundBuilder_ == null) {
          return sound_ == null ? de.bwueller.environment.protocol.PlaySound.Sound.getDefaultInstance() : sound_;
        } else {
          return soundBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Sound sound = 4;</code>
       */
      public Builder setSound(de.bwueller.environment.protocol.PlaySound.Sound value) {
        if (soundBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sound_ = value;
          onChanged();
        } else {
          soundBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Sound sound = 4;</code>
       */
      public Builder setSound(
          de.bwueller.environment.protocol.PlaySound.Sound.Builder builderForValue) {
        if (soundBuilder_ == null) {
          sound_ = builderForValue.build();
          onChanged();
        } else {
          soundBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Sound sound = 4;</code>
       */
      public Builder mergeSound(de.bwueller.environment.protocol.PlaySound.Sound value) {
        if (soundBuilder_ == null) {
          if (sound_ != null) {
            sound_ =
              de.bwueller.environment.protocol.PlaySound.Sound.newBuilder(sound_).mergeFrom(value).buildPartial();
          } else {
            sound_ = value;
          }
          onChanged();
        } else {
          soundBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Sound sound = 4;</code>
       */
      public Builder clearSound() {
        if (soundBuilder_ == null) {
          sound_ = null;
          onChanged();
        } else {
          sound_ = null;
          soundBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Sound sound = 4;</code>
       */
      public de.bwueller.environment.protocol.PlaySound.Sound.Builder getSoundBuilder() {
        
        onChanged();
        return getSoundFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Sound sound = 4;</code>
       */
      public de.bwueller.environment.protocol.PlaySound.SoundOrBuilder getSoundOrBuilder() {
        if (soundBuilder_ != null) {
          return soundBuilder_.getMessageOrBuilder();
        } else {
          return sound_ == null ?
              de.bwueller.environment.protocol.PlaySound.Sound.getDefaultInstance() : sound_;
        }
      }
      /**
       * <code>optional .Sound sound = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.PlaySound.Sound, de.bwueller.environment.protocol.PlaySound.Sound.Builder, de.bwueller.environment.protocol.PlaySound.SoundOrBuilder> 
          getSoundFieldBuilder() {
        if (soundBuilder_ == null) {
          soundBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              de.bwueller.environment.protocol.PlaySound.Sound, de.bwueller.environment.protocol.PlaySound.Sound.Builder, de.bwueller.environment.protocol.PlaySound.SoundOrBuilder>(
                  getSound(),
                  getParentForChildren(),
                  isClean());
          sound_ = null;
        }
        return soundBuilder_;
      }

      private double volume_ ;
      /**
       * <code>optional double volume = 5;</code>
       */
      public double getVolume() {
        return volume_;
      }
      /**
       * <code>optional double volume = 5;</code>
       */
      public Builder setVolume(double value) {
        
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double volume = 5;</code>
       */
      public Builder clearVolume() {
        
        volume_ = 0D;
        onChanged();
        return this;
      }

      private double rate_ ;
      /**
       * <code>optional double rate = 6;</code>
       */
      public double getRate() {
        return rate_;
      }
      /**
       * <code>optional double rate = 6;</code>
       */
      public Builder setRate(double value) {
        
        rate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double rate = 6;</code>
       */
      public Builder clearRate() {
        
        rate_ = 0D;
        onChanged();
        return this;
      }

      private boolean loop_ ;
      /**
       * <code>optional bool loop = 7;</code>
       */
      public boolean getLoop() {
        return loop_;
      }
      /**
       * <code>optional bool loop = 7;</code>
       */
      public Builder setLoop(boolean value) {
        
        loop_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool loop = 7;</code>
       */
      public Builder clearLoop() {
        
        loop_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PlaySoundRequest)
    }

    // @@protoc_insertion_point(class_scope:PlaySoundRequest)
    private static final de.bwueller.environment.protocol.PlaySound.PlaySoundRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.bwueller.environment.protocol.PlaySound.PlaySoundRequest();
    }

    public static de.bwueller.environment.protocol.PlaySound.PlaySoundRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlaySoundRequest>
        PARSER = new com.google.protobuf.AbstractParser<PlaySoundRequest>() {
      public PlaySoundRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlaySoundRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlaySoundRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlaySoundRequest> getParserForType() {
      return PARSER;
    }

    public de.bwueller.environment.protocol.PlaySound.PlaySoundRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlaySoundResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlaySoundResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .UUID identifier = 1;</code>
     */
    boolean hasIdentifier();
    /**
     * <code>optional .UUID identifier = 1;</code>
     */
    de.bwueller.environment.protocol.General.UUID getIdentifier();
    /**
     * <code>optional .UUID identifier = 1;</code>
     */
    de.bwueller.environment.protocol.General.UUIDOrBuilder getIdentifierOrBuilder();
  }
  /**
   * Protobuf type {@code PlaySoundResponse}
   */
  public  static final class PlaySoundResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlaySoundResponse)
      PlaySoundResponseOrBuilder {
    // Use PlaySoundResponse.newBuilder() to construct.
    private PlaySoundResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlaySoundResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PlaySoundResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              de.bwueller.environment.protocol.General.UUID.Builder subBuilder = null;
              if (identifier_ != null) {
                subBuilder = identifier_.toBuilder();
              }
              identifier_ = input.readMessage(de.bwueller.environment.protocol.General.UUID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(identifier_);
                identifier_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.bwueller.environment.protocol.PlaySound.internal_static_PlaySoundResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.bwueller.environment.protocol.PlaySound.internal_static_PlaySoundResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.bwueller.environment.protocol.PlaySound.PlaySoundResponse.class, de.bwueller.environment.protocol.PlaySound.PlaySoundResponse.Builder.class);
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 1;
    private de.bwueller.environment.protocol.General.UUID identifier_;
    /**
     * <code>optional .UUID identifier = 1;</code>
     */
    public boolean hasIdentifier() {
      return identifier_ != null;
    }
    /**
     * <code>optional .UUID identifier = 1;</code>
     */
    public de.bwueller.environment.protocol.General.UUID getIdentifier() {
      return identifier_ == null ? de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : identifier_;
    }
    /**
     * <code>optional .UUID identifier = 1;</code>
     */
    public de.bwueller.environment.protocol.General.UUIDOrBuilder getIdentifierOrBuilder() {
      return getIdentifier();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (identifier_ != null) {
        output.writeMessage(1, getIdentifier());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (identifier_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getIdentifier());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.bwueller.environment.protocol.PlaySound.PlaySoundResponse)) {
        return super.equals(obj);
      }
      de.bwueller.environment.protocol.PlaySound.PlaySoundResponse other = (de.bwueller.environment.protocol.PlaySound.PlaySoundResponse) obj;

      boolean result = true;
      result = result && (hasIdentifier() == other.hasIdentifier());
      if (hasIdentifier()) {
        result = result && getIdentifier()
            .equals(other.getIdentifier());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasIdentifier()) {
        hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getIdentifier().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.bwueller.environment.protocol.PlaySound.PlaySoundResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.PlaySound.PlaySoundResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.bwueller.environment.protocol.PlaySound.PlaySoundResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlaySoundResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlaySoundResponse)
        de.bwueller.environment.protocol.PlaySound.PlaySoundResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.bwueller.environment.protocol.PlaySound.internal_static_PlaySoundResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.bwueller.environment.protocol.PlaySound.internal_static_PlaySoundResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.bwueller.environment.protocol.PlaySound.PlaySoundResponse.class, de.bwueller.environment.protocol.PlaySound.PlaySoundResponse.Builder.class);
      }

      // Construct using de.bwueller.environment.protocol.PlaySound.PlaySoundResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (identifierBuilder_ == null) {
          identifier_ = null;
        } else {
          identifier_ = null;
          identifierBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.bwueller.environment.protocol.PlaySound.internal_static_PlaySoundResponse_descriptor;
      }

      public de.bwueller.environment.protocol.PlaySound.PlaySoundResponse getDefaultInstanceForType() {
        return de.bwueller.environment.protocol.PlaySound.PlaySoundResponse.getDefaultInstance();
      }

      public de.bwueller.environment.protocol.PlaySound.PlaySoundResponse build() {
        de.bwueller.environment.protocol.PlaySound.PlaySoundResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.bwueller.environment.protocol.PlaySound.PlaySoundResponse buildPartial() {
        de.bwueller.environment.protocol.PlaySound.PlaySoundResponse result = new de.bwueller.environment.protocol.PlaySound.PlaySoundResponse(this);
        if (identifierBuilder_ == null) {
          result.identifier_ = identifier_;
        } else {
          result.identifier_ = identifierBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.bwueller.environment.protocol.PlaySound.PlaySoundResponse) {
          return mergeFrom((de.bwueller.environment.protocol.PlaySound.PlaySoundResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.bwueller.environment.protocol.PlaySound.PlaySoundResponse other) {
        if (other == de.bwueller.environment.protocol.PlaySound.PlaySoundResponse.getDefaultInstance()) return this;
        if (other.hasIdentifier()) {
          mergeIdentifier(other.getIdentifier());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.bwueller.environment.protocol.PlaySound.PlaySoundResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.bwueller.environment.protocol.PlaySound.PlaySoundResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private de.bwueller.environment.protocol.General.UUID identifier_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder> identifierBuilder_;
      /**
       * <code>optional .UUID identifier = 1;</code>
       */
      public boolean hasIdentifier() {
        return identifierBuilder_ != null || identifier_ != null;
      }
      /**
       * <code>optional .UUID identifier = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUID getIdentifier() {
        if (identifierBuilder_ == null) {
          return identifier_ == null ? de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : identifier_;
        } else {
          return identifierBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .UUID identifier = 1;</code>
       */
      public Builder setIdentifier(de.bwueller.environment.protocol.General.UUID value) {
        if (identifierBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          identifier_ = value;
          onChanged();
        } else {
          identifierBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .UUID identifier = 1;</code>
       */
      public Builder setIdentifier(
          de.bwueller.environment.protocol.General.UUID.Builder builderForValue) {
        if (identifierBuilder_ == null) {
          identifier_ = builderForValue.build();
          onChanged();
        } else {
          identifierBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .UUID identifier = 1;</code>
       */
      public Builder mergeIdentifier(de.bwueller.environment.protocol.General.UUID value) {
        if (identifierBuilder_ == null) {
          if (identifier_ != null) {
            identifier_ =
              de.bwueller.environment.protocol.General.UUID.newBuilder(identifier_).mergeFrom(value).buildPartial();
          } else {
            identifier_ = value;
          }
          onChanged();
        } else {
          identifierBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .UUID identifier = 1;</code>
       */
      public Builder clearIdentifier() {
        if (identifierBuilder_ == null) {
          identifier_ = null;
          onChanged();
        } else {
          identifier_ = null;
          identifierBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .UUID identifier = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUID.Builder getIdentifierBuilder() {
        
        onChanged();
        return getIdentifierFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UUID identifier = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUIDOrBuilder getIdentifierOrBuilder() {
        if (identifierBuilder_ != null) {
          return identifierBuilder_.getMessageOrBuilder();
        } else {
          return identifier_ == null ?
              de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : identifier_;
        }
      }
      /**
       * <code>optional .UUID identifier = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder> 
          getIdentifierFieldBuilder() {
        if (identifierBuilder_ == null) {
          identifierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder>(
                  getIdentifier(),
                  getParentForChildren(),
                  isClean());
          identifier_ = null;
        }
        return identifierBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PlaySoundResponse)
    }

    // @@protoc_insertion_point(class_scope:PlaySoundResponse)
    private static final de.bwueller.environment.protocol.PlaySound.PlaySoundResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.bwueller.environment.protocol.PlaySound.PlaySoundResponse();
    }

    public static de.bwueller.environment.protocol.PlaySound.PlaySoundResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlaySoundResponse>
        PARSER = new com.google.protobuf.AbstractParser<PlaySoundResponse>() {
      public PlaySoundResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlaySoundResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlaySoundResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlaySoundResponse> getParserForType() {
      return PARSER;
    }

    public de.bwueller.environment.protocol.PlaySound.PlaySoundResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SoundOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Sound)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string category = 1;</code>
     */
    java.lang.String getCategory();
    /**
     * <code>optional string category = 1;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Sound}
   */
  public  static final class Sound extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Sound)
      SoundOrBuilder {
    // Use Sound.newBuilder() to construct.
    private Sound(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sound() {
      category_ = "";
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Sound(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              category_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.bwueller.environment.protocol.PlaySound.internal_static_Sound_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.bwueller.environment.protocol.PlaySound.internal_static_Sound_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.bwueller.environment.protocol.PlaySound.Sound.class, de.bwueller.environment.protocol.PlaySound.Sound.Builder.class);
    }

    public static final int CATEGORY_FIELD_NUMBER = 1;
    private volatile java.lang.Object category_;
    /**
     * <code>optional string category = 1;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      }
    }
    /**
     * <code>optional string category = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCategoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, category_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCategoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, category_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.bwueller.environment.protocol.PlaySound.Sound)) {
        return super.equals(obj);
      }
      de.bwueller.environment.protocol.PlaySound.Sound other = (de.bwueller.environment.protocol.PlaySound.Sound) obj;

      boolean result = true;
      result = result && getCategory()
          .equals(other.getCategory());
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.bwueller.environment.protocol.PlaySound.Sound parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.PlaySound.Sound parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.Sound parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.PlaySound.Sound parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.Sound parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.PlaySound.Sound parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.Sound parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.PlaySound.Sound parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.PlaySound.Sound parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.PlaySound.Sound parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.bwueller.environment.protocol.PlaySound.Sound prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Sound}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Sound)
        de.bwueller.environment.protocol.PlaySound.SoundOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.bwueller.environment.protocol.PlaySound.internal_static_Sound_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.bwueller.environment.protocol.PlaySound.internal_static_Sound_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.bwueller.environment.protocol.PlaySound.Sound.class, de.bwueller.environment.protocol.PlaySound.Sound.Builder.class);
      }

      // Construct using de.bwueller.environment.protocol.PlaySound.Sound.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        category_ = "";

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.bwueller.environment.protocol.PlaySound.internal_static_Sound_descriptor;
      }

      public de.bwueller.environment.protocol.PlaySound.Sound getDefaultInstanceForType() {
        return de.bwueller.environment.protocol.PlaySound.Sound.getDefaultInstance();
      }

      public de.bwueller.environment.protocol.PlaySound.Sound build() {
        de.bwueller.environment.protocol.PlaySound.Sound result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.bwueller.environment.protocol.PlaySound.Sound buildPartial() {
        de.bwueller.environment.protocol.PlaySound.Sound result = new de.bwueller.environment.protocol.PlaySound.Sound(this);
        result.category_ = category_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.bwueller.environment.protocol.PlaySound.Sound) {
          return mergeFrom((de.bwueller.environment.protocol.PlaySound.Sound)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.bwueller.environment.protocol.PlaySound.Sound other) {
        if (other == de.bwueller.environment.protocol.PlaySound.Sound.getDefaultInstance()) return this;
        if (!other.getCategory().isEmpty()) {
          category_ = other.category_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.bwueller.environment.protocol.PlaySound.Sound parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.bwueller.environment.protocol.PlaySound.Sound) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <code>optional string category = 1;</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string category = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string category = 1;</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 1;</code>
       */
      public Builder clearCategory() {
        
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 1;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        category_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Sound)
    }

    // @@protoc_insertion_point(class_scope:Sound)
    private static final de.bwueller.environment.protocol.PlaySound.Sound DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.bwueller.environment.protocol.PlaySound.Sound();
    }

    public static de.bwueller.environment.protocol.PlaySound.Sound getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sound>
        PARSER = new com.google.protobuf.AbstractParser<Sound>() {
      public Sound parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Sound(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Sound> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sound> getParserForType() {
      return PARSER;
    }

    public de.bwueller.environment.protocol.PlaySound.Sound getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlaySoundRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlaySoundRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlaySoundResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlaySoundResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sound_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Sound_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020play_sound.proto\032\rgeneral.proto\"\234\001\n\020Pl" +
      "aySoundRequest\022\023\n\004user\030\001 \001(\0132\005.UUID\022\031\n\ni" +
      "dentifier\030\002 \001(\0132\005.UUID\022\025\n\005intro\030\003 \001(\0132\006." +
      "Sound\022\025\n\005sound\030\004 \001(\0132\006.Sound\022\016\n\006volume\030\005" +
      " \001(\001\022\014\n\004rate\030\006 \001(\001\022\014\n\004loop\030\007 \001(\010\".\n\021Play" +
      "SoundResponse\022\031\n\nidentifier\030\001 \001(\0132\005.UUID" +
      "\"\'\n\005Sound\022\020\n\010category\030\001 \001(\t\022\014\n\004name\030\002 \001(" +
      "\tB\"\n de.bwueller.environment.protocolb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.bwueller.environment.protocol.General.getDescriptor(),
        }, assigner);
    internal_static_PlaySoundRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlaySoundRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlaySoundRequest_descriptor,
        new java.lang.String[] { "User", "Identifier", "Intro", "Sound", "Volume", "Rate", "Loop", });
    internal_static_PlaySoundResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PlaySoundResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlaySoundResponse_descriptor,
        new java.lang.String[] { "Identifier", });
    internal_static_Sound_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Sound_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Sound_descriptor,
        new java.lang.String[] { "Category", "Name", });
    de.bwueller.environment.protocol.General.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
