// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_sound_volume.proto

package de.bwueller.environment.protocol;

public final class UpdateSoundVolume {
  private UpdateSoundVolume() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateSoundVolumeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UpdateSoundVolumeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional .UUID sound = 1;</code>
     */
    boolean hasSound();
    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional .UUID sound = 1;</code>
     */
    de.bwueller.environment.protocol.General.UUID getSound();
    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional .UUID sound = 1;</code>
     */
    de.bwueller.environment.protocol.General.UUIDOrBuilder getSoundOrBuilder();

    /**
     * <code>optional double volume = 2;</code>
     */
    double getVolume();

    /**
     * <code>optional uint32 duration = 3;</code>
     */
    int getDuration();
  }
  /**
   * Protobuf type {@code UpdateSoundVolumeRequest}
   */
  public  static final class UpdateSoundVolumeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UpdateSoundVolumeRequest)
      UpdateSoundVolumeRequestOrBuilder {
    // Use UpdateSoundVolumeRequest.newBuilder() to construct.
    private UpdateSoundVolumeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateSoundVolumeRequest() {
      volume_ = 0D;
      duration_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateSoundVolumeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              de.bwueller.environment.protocol.General.UUID.Builder subBuilder = null;
              if (sound_ != null) {
                subBuilder = sound_.toBuilder();
              }
              sound_ = input.readMessage(de.bwueller.environment.protocol.General.UUID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sound_);
                sound_ = subBuilder.buildPartial();
              }

              break;
            }
            case 17: {

              volume_ = input.readDouble();
              break;
            }
            case 24: {

              duration_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.bwueller.environment.protocol.UpdateSoundVolume.internal_static_UpdateSoundVolumeRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.bwueller.environment.protocol.UpdateSoundVolume.internal_static_UpdateSoundVolumeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest.class, de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest.Builder.class);
    }

    public static final int SOUND_FIELD_NUMBER = 1;
    private de.bwueller.environment.protocol.General.UUID sound_;
    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional .UUID sound = 1;</code>
     */
    public boolean hasSound() {
      return sound_ != null;
    }
    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional .UUID sound = 1;</code>
     */
    public de.bwueller.environment.protocol.General.UUID getSound() {
      return sound_ == null ? de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : sound_;
    }
    /**
     * <pre>
     * Sound identifier.
     * </pre>
     *
     * <code>optional .UUID sound = 1;</code>
     */
    public de.bwueller.environment.protocol.General.UUIDOrBuilder getSoundOrBuilder() {
      return getSound();
    }

    public static final int VOLUME_FIELD_NUMBER = 2;
    private double volume_;
    /**
     * <code>optional double volume = 2;</code>
     */
    public double getVolume() {
      return volume_;
    }

    public static final int DURATION_FIELD_NUMBER = 3;
    private int duration_;
    /**
     * <code>optional uint32 duration = 3;</code>
     */
    public int getDuration() {
      return duration_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sound_ != null) {
        output.writeMessage(1, getSound());
      }
      if (volume_ != 0D) {
        output.writeDouble(2, volume_);
      }
      if (duration_ != 0) {
        output.writeUInt32(3, duration_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sound_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSound());
      }
      if (volume_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, volume_);
      }
      if (duration_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, duration_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest)) {
        return super.equals(obj);
      }
      de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest other = (de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest) obj;

      boolean result = true;
      result = result && (hasSound() == other.hasSound());
      if (hasSound()) {
        result = result && getSound()
            .equals(other.getSound());
      }
      result = result && (
          java.lang.Double.doubleToLongBits(getVolume())
          == java.lang.Double.doubleToLongBits(
              other.getVolume()));
      result = result && (getDuration()
          == other.getDuration());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSound()) {
        hash = (37 * hash) + SOUND_FIELD_NUMBER;
        hash = (53 * hash) + getSound().hashCode();
      }
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVolume()));
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getDuration();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UpdateSoundVolumeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UpdateSoundVolumeRequest)
        de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.bwueller.environment.protocol.UpdateSoundVolume.internal_static_UpdateSoundVolumeRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.bwueller.environment.protocol.UpdateSoundVolume.internal_static_UpdateSoundVolumeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest.class, de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest.Builder.class);
      }

      // Construct using de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (soundBuilder_ == null) {
          sound_ = null;
        } else {
          sound_ = null;
          soundBuilder_ = null;
        }
        volume_ = 0D;

        duration_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.bwueller.environment.protocol.UpdateSoundVolume.internal_static_UpdateSoundVolumeRequest_descriptor;
      }

      public de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest getDefaultInstanceForType() {
        return de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest.getDefaultInstance();
      }

      public de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest build() {
        de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest buildPartial() {
        de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest result = new de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest(this);
        if (soundBuilder_ == null) {
          result.sound_ = sound_;
        } else {
          result.sound_ = soundBuilder_.build();
        }
        result.volume_ = volume_;
        result.duration_ = duration_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest) {
          return mergeFrom((de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest other) {
        if (other == de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest.getDefaultInstance()) return this;
        if (other.hasSound()) {
          mergeSound(other.getSound());
        }
        if (other.getVolume() != 0D) {
          setVolume(other.getVolume());
        }
        if (other.getDuration() != 0) {
          setDuration(other.getDuration());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private de.bwueller.environment.protocol.General.UUID sound_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder> soundBuilder_;
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional .UUID sound = 1;</code>
       */
      public boolean hasSound() {
        return soundBuilder_ != null || sound_ != null;
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional .UUID sound = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUID getSound() {
        if (soundBuilder_ == null) {
          return sound_ == null ? de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : sound_;
        } else {
          return soundBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional .UUID sound = 1;</code>
       */
      public Builder setSound(de.bwueller.environment.protocol.General.UUID value) {
        if (soundBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sound_ = value;
          onChanged();
        } else {
          soundBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional .UUID sound = 1;</code>
       */
      public Builder setSound(
          de.bwueller.environment.protocol.General.UUID.Builder builderForValue) {
        if (soundBuilder_ == null) {
          sound_ = builderForValue.build();
          onChanged();
        } else {
          soundBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional .UUID sound = 1;</code>
       */
      public Builder mergeSound(de.bwueller.environment.protocol.General.UUID value) {
        if (soundBuilder_ == null) {
          if (sound_ != null) {
            sound_ =
              de.bwueller.environment.protocol.General.UUID.newBuilder(sound_).mergeFrom(value).buildPartial();
          } else {
            sound_ = value;
          }
          onChanged();
        } else {
          soundBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional .UUID sound = 1;</code>
       */
      public Builder clearSound() {
        if (soundBuilder_ == null) {
          sound_ = null;
          onChanged();
        } else {
          sound_ = null;
          soundBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional .UUID sound = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUID.Builder getSoundBuilder() {
        
        onChanged();
        return getSoundFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional .UUID sound = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUIDOrBuilder getSoundOrBuilder() {
        if (soundBuilder_ != null) {
          return soundBuilder_.getMessageOrBuilder();
        } else {
          return sound_ == null ?
              de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : sound_;
        }
      }
      /**
       * <pre>
       * Sound identifier.
       * </pre>
       *
       * <code>optional .UUID sound = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder> 
          getSoundFieldBuilder() {
        if (soundBuilder_ == null) {
          soundBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder>(
                  getSound(),
                  getParentForChildren(),
                  isClean());
          sound_ = null;
        }
        return soundBuilder_;
      }

      private double volume_ ;
      /**
       * <code>optional double volume = 2;</code>
       */
      public double getVolume() {
        return volume_;
      }
      /**
       * <code>optional double volume = 2;</code>
       */
      public Builder setVolume(double value) {
        
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double volume = 2;</code>
       */
      public Builder clearVolume() {
        
        volume_ = 0D;
        onChanged();
        return this;
      }

      private int duration_ ;
      /**
       * <code>optional uint32 duration = 3;</code>
       */
      public int getDuration() {
        return duration_;
      }
      /**
       * <code>optional uint32 duration = 3;</code>
       */
      public Builder setDuration(int value) {
        
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 duration = 3;</code>
       */
      public Builder clearDuration() {
        
        duration_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UpdateSoundVolumeRequest)
    }

    // @@protoc_insertion_point(class_scope:UpdateSoundVolumeRequest)
    private static final de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest();
    }

    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateSoundVolumeRequest>
        PARSER = new com.google.protobuf.AbstractParser<UpdateSoundVolumeRequest>() {
      public UpdateSoundVolumeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdateSoundVolumeRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateSoundVolumeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateSoundVolumeRequest> getParserForType() {
      return PARSER;
    }

    public de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateSoundVolumeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UpdateSoundVolumeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .UUID sound = 1;</code>
     */
    boolean hasSound();
    /**
     * <code>optional .UUID sound = 1;</code>
     */
    de.bwueller.environment.protocol.General.UUID getSound();
    /**
     * <code>optional .UUID sound = 1;</code>
     */
    de.bwueller.environment.protocol.General.UUIDOrBuilder getSoundOrBuilder();

    /**
     * <code>optional double volume = 2;</code>
     */
    double getVolume();
  }
  /**
   * Protobuf type {@code UpdateSoundVolumeResponse}
   */
  public  static final class UpdateSoundVolumeResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UpdateSoundVolumeResponse)
      UpdateSoundVolumeResponseOrBuilder {
    // Use UpdateSoundVolumeResponse.newBuilder() to construct.
    private UpdateSoundVolumeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateSoundVolumeResponse() {
      volume_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateSoundVolumeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              de.bwueller.environment.protocol.General.UUID.Builder subBuilder = null;
              if (sound_ != null) {
                subBuilder = sound_.toBuilder();
              }
              sound_ = input.readMessage(de.bwueller.environment.protocol.General.UUID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sound_);
                sound_ = subBuilder.buildPartial();
              }

              break;
            }
            case 17: {

              volume_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.bwueller.environment.protocol.UpdateSoundVolume.internal_static_UpdateSoundVolumeResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.bwueller.environment.protocol.UpdateSoundVolume.internal_static_UpdateSoundVolumeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse.class, de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse.Builder.class);
    }

    public static final int SOUND_FIELD_NUMBER = 1;
    private de.bwueller.environment.protocol.General.UUID sound_;
    /**
     * <code>optional .UUID sound = 1;</code>
     */
    public boolean hasSound() {
      return sound_ != null;
    }
    /**
     * <code>optional .UUID sound = 1;</code>
     */
    public de.bwueller.environment.protocol.General.UUID getSound() {
      return sound_ == null ? de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : sound_;
    }
    /**
     * <code>optional .UUID sound = 1;</code>
     */
    public de.bwueller.environment.protocol.General.UUIDOrBuilder getSoundOrBuilder() {
      return getSound();
    }

    public static final int VOLUME_FIELD_NUMBER = 2;
    private double volume_;
    /**
     * <code>optional double volume = 2;</code>
     */
    public double getVolume() {
      return volume_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sound_ != null) {
        output.writeMessage(1, getSound());
      }
      if (volume_ != 0D) {
        output.writeDouble(2, volume_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sound_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSound());
      }
      if (volume_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, volume_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse)) {
        return super.equals(obj);
      }
      de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse other = (de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse) obj;

      boolean result = true;
      result = result && (hasSound() == other.hasSound());
      if (hasSound()) {
        result = result && getSound()
            .equals(other.getSound());
      }
      result = result && (
          java.lang.Double.doubleToLongBits(getVolume())
          == java.lang.Double.doubleToLongBits(
              other.getVolume()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSound()) {
        hash = (37 * hash) + SOUND_FIELD_NUMBER;
        hash = (53 * hash) + getSound().hashCode();
      }
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVolume()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UpdateSoundVolumeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UpdateSoundVolumeResponse)
        de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.bwueller.environment.protocol.UpdateSoundVolume.internal_static_UpdateSoundVolumeResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.bwueller.environment.protocol.UpdateSoundVolume.internal_static_UpdateSoundVolumeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse.class, de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse.Builder.class);
      }

      // Construct using de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (soundBuilder_ == null) {
          sound_ = null;
        } else {
          sound_ = null;
          soundBuilder_ = null;
        }
        volume_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.bwueller.environment.protocol.UpdateSoundVolume.internal_static_UpdateSoundVolumeResponse_descriptor;
      }

      public de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse getDefaultInstanceForType() {
        return de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse.getDefaultInstance();
      }

      public de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse build() {
        de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse buildPartial() {
        de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse result = new de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse(this);
        if (soundBuilder_ == null) {
          result.sound_ = sound_;
        } else {
          result.sound_ = soundBuilder_.build();
        }
        result.volume_ = volume_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse) {
          return mergeFrom((de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse other) {
        if (other == de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse.getDefaultInstance()) return this;
        if (other.hasSound()) {
          mergeSound(other.getSound());
        }
        if (other.getVolume() != 0D) {
          setVolume(other.getVolume());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private de.bwueller.environment.protocol.General.UUID sound_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder> soundBuilder_;
      /**
       * <code>optional .UUID sound = 1;</code>
       */
      public boolean hasSound() {
        return soundBuilder_ != null || sound_ != null;
      }
      /**
       * <code>optional .UUID sound = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUID getSound() {
        if (soundBuilder_ == null) {
          return sound_ == null ? de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : sound_;
        } else {
          return soundBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .UUID sound = 1;</code>
       */
      public Builder setSound(de.bwueller.environment.protocol.General.UUID value) {
        if (soundBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sound_ = value;
          onChanged();
        } else {
          soundBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .UUID sound = 1;</code>
       */
      public Builder setSound(
          de.bwueller.environment.protocol.General.UUID.Builder builderForValue) {
        if (soundBuilder_ == null) {
          sound_ = builderForValue.build();
          onChanged();
        } else {
          soundBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .UUID sound = 1;</code>
       */
      public Builder mergeSound(de.bwueller.environment.protocol.General.UUID value) {
        if (soundBuilder_ == null) {
          if (sound_ != null) {
            sound_ =
              de.bwueller.environment.protocol.General.UUID.newBuilder(sound_).mergeFrom(value).buildPartial();
          } else {
            sound_ = value;
          }
          onChanged();
        } else {
          soundBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .UUID sound = 1;</code>
       */
      public Builder clearSound() {
        if (soundBuilder_ == null) {
          sound_ = null;
          onChanged();
        } else {
          sound_ = null;
          soundBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .UUID sound = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUID.Builder getSoundBuilder() {
        
        onChanged();
        return getSoundFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UUID sound = 1;</code>
       */
      public de.bwueller.environment.protocol.General.UUIDOrBuilder getSoundOrBuilder() {
        if (soundBuilder_ != null) {
          return soundBuilder_.getMessageOrBuilder();
        } else {
          return sound_ == null ?
              de.bwueller.environment.protocol.General.UUID.getDefaultInstance() : sound_;
        }
      }
      /**
       * <code>optional .UUID sound = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder> 
          getSoundFieldBuilder() {
        if (soundBuilder_ == null) {
          soundBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              de.bwueller.environment.protocol.General.UUID, de.bwueller.environment.protocol.General.UUID.Builder, de.bwueller.environment.protocol.General.UUIDOrBuilder>(
                  getSound(),
                  getParentForChildren(),
                  isClean());
          sound_ = null;
        }
        return soundBuilder_;
      }

      private double volume_ ;
      /**
       * <code>optional double volume = 2;</code>
       */
      public double getVolume() {
        return volume_;
      }
      /**
       * <code>optional double volume = 2;</code>
       */
      public Builder setVolume(double value) {
        
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double volume = 2;</code>
       */
      public Builder clearVolume() {
        
        volume_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UpdateSoundVolumeResponse)
    }

    // @@protoc_insertion_point(class_scope:UpdateSoundVolumeResponse)
    private static final de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse();
    }

    public static de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateSoundVolumeResponse>
        PARSER = new com.google.protobuf.AbstractParser<UpdateSoundVolumeResponse>() {
      public UpdateSoundVolumeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdateSoundVolumeResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateSoundVolumeResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateSoundVolumeResponse> getParserForType() {
      return PARSER;
    }

    public de.bwueller.environment.protocol.UpdateSoundVolume.UpdateSoundVolumeResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateSoundVolumeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateSoundVolumeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateSoundVolumeResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateSoundVolumeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031update_sound_volume.proto\032\rgeneral.pro" +
      "to\"R\n\030UpdateSoundVolumeRequest\022\024\n\005sound\030" +
      "\001 \001(\0132\005.UUID\022\016\n\006volume\030\002 \001(\001\022\020\n\010duration" +
      "\030\003 \001(\r\"A\n\031UpdateSoundVolumeResponse\022\024\n\005s" +
      "ound\030\001 \001(\0132\005.UUID\022\016\n\006volume\030\002 \001(\001B\"\n de." +
      "bwueller.environment.protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.bwueller.environment.protocol.General.getDescriptor(),
        }, assigner);
    internal_static_UpdateSoundVolumeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UpdateSoundVolumeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateSoundVolumeRequest_descriptor,
        new java.lang.String[] { "Sound", "Volume", "Duration", });
    internal_static_UpdateSoundVolumeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UpdateSoundVolumeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateSoundVolumeResponse_descriptor,
        new java.lang.String[] { "Sound", "Volume", });
    de.bwueller.environment.protocol.General.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
