package de.bwueller.environment.actor.api

import java.net.URI
import java.util.*

class ActorApi {

  // TODO: add config

  companion object {

    private val config: Config = Config.load()
    private var client = Client(config.name, URI.create(config.processorAddress))

    internal val soundManager = SoundManager(client)
    internal val userManager = UserManager(client)

    private val listeners = mutableListOf<(Boolean) -> Unit>()

    init {
      addListener { connected ->
        if (!connected) {
          Thread({
            Thread.sleep(10000)
            client = Client(config.name, URI.create(config.processorAddress))
            soundManager.client = client
            userManager.client = client
          }).start()
        }
      }
    }

    internal fun setConnected(connected: Boolean, identifier: UUID?) {
      this.identifier = identifier
      this.isConnected = connected
    }

    /**
     * Defines whether the actor is connected to the processor.
     */
    @JvmStatic
    var isConnected = false
      private set(value) = listeners.forEach { it.invoke(value) }

    /**
     * Defines the unique identifier for this actor generated by the processor. {@code null} if
     * not connected.
     */
    @JvmStatic
    var identifier: UUID? = null
      private set

    /**
     * Adds a listener invoked when the actor connects to or disconnects from the processor.
     *
     * @param listener the listener to invoke.
     */
    @JvmStatic
    fun addListener(listener: (Boolean) -> Unit) {
      listeners.add(listener)
    }

    /**
     * Removes the listener.
     *
     * @param listener the listener to remove.
     */
    @JvmStatic
    fun removeListener(listener: (Boolean) -> Unit) {
      listeners.remove(listener)
    }

    @JvmStatic
    fun registerUser(user: String,
                     registerCallback: (user: String, key: String) -> Unit,
                     connectCallback: ((user: String, connected: Boolean) -> Unit)? = null) {
      userManager.registerUser(user, registerCallback, connectCallback)
    }

    @JvmStatic
    fun unregisterUser(user: String) = userManager.unregisterUser(user)

    @JvmStatic
    fun isUserRegistered(user: String) = userManager.isUserRegistered(user)

    @JvmStatic
    fun isUserConnected(user: String) = userManager.isUserConnected(user)

    @JvmStatic
    fun main(args: Array<String>) {
      addListener { connected ->
        registerUser("Bw2801", { user, key ->
          println("$user, $key")
        }, { user, connected ->
          if (connected) {
            val sound = Sound(null, "mac_leod.frozen_star", 0.0)
            sound.play(user)

            Thread.sleep(2000)
            sound.fadeToVolume(1.0, 2000)
          }
        })
      }
    }
  }
}
